on:
  workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-22.04
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Extract environment variables
      id: vars
      run: echo "VAR1=foo" >> $GITHUB_ENV

    - name : ssh
      uses: appleboy/ssh-action@v1.2.0
      envs:
        VAR1: ${{ steps.vars.outputs.VAR1 }}
      with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: VAR1
          run: echo "var1 is $VAR1"

