on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: add env var
        run: echo "API_KEY=123" >> $GITHUB_ENV

      - name: ssh
        uses: appleboy/ssh-action@v1.2.0
        env:
          API_KEY=${{ env.API_KEY }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: API_KEY
        script: |
          echo $API_KEY
          echo "Hello World"